### ISSUE TITLE
CreateManagedPrefixList operation: Must specify a max size between 1 and 1000 error

### ISSUE THREAD

**Issue by on4jo** [aws-samples/update-aws-ip-ranges#1]
I need to create a VPC prefix list that we can use to allow SNS traffic. There isn't a specific Service for SNS[1], this mean we can only create a list based on the Service 'AMAZON'. The total list of IP ranges for AMAZON is more than 4000, and we reach the limit of one VPC managed prefix list.
Would it be possible to have an update that could create more than one managed VPC list for a Service, like AMAZON Service?

service.json:
{
    "Services": [
        {
            "Name": "AMAZON",
            "Regions": [],
            "PrefixList": {
                "Enable": true,
                "Summarize": false
            }
        }
    ]
}

Error: 
[ERROR]	2023-03-20T06:42:53.439Z	86b72da5-264b-46e5-ad11-b4557d859513	An error occurred (InvalidParameterValue) when calling the CreateManagedPrefixList operation: Must specify a max size between 1 and 1000
Traceback (most recent call last):
  File "/var/task/update_aws_ip_ranges.py", line 793, in lambda_handler
    prefix_list_names: dict[str, list[str]] = manage_prefix_list(ec2_client, vpc_prefix_lists, service_name, service_ranges, should_summarize)
  File "/var/task/update_aws_ip_ranges.py", line 459, in manage_prefix_list
    create_prefix_list(client, prefix_list_name, ip_version.upper(), address_list)
  File "/var/task/update_aws_ip_ranges.py", line 533, in create_prefix_list
    response = client.create_managed_prefix_list(
  File "/var/runtime/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CreateManagedPrefixList operation: Must specify a max size between 1 and 1000

[1] https://aws.amazon.com/premiumsupport/knowledge-center/sns-ip-address-range/

Regards,
Johan Gillis

**Comment by lazize** [comment]
Can you explain more about your architecture?
Which service do you want to use this prefix list?
Is it inbound or outbound?

I understood it is for an HTTP/HTTPS endpoint you are configuring on SNS. Endpoint is on AWS.

**Comment by on4jo** [comment]
We have a ticketing solution running after an application load balancer listening on port 5811. From another account we use SNS to send request to this ALB over https. We do not want to allow 0.0.0.0/0 but only the AWS subnet for SNS. There is no SNS Service Name in the ip_ranges.json according to AWS you will need to use 'AMAZON' service but this is about 4419 IP ranges.

**Comment by lazize** [comment]
As you are using ALB, you can use WAF IPSet, which support up-to 10k addresses on each IPSet.

ENI doesn't support more than 1k rules associated with it. See it below.  
https://aws.amazon.com/premiumsupport/knowledge-center/increase-security-group-rule-limit/
